// <auto-generated />
using System;
using Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029163145_Modelo-Inicial-Datos")]
    partial class ModeloInicialDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("TipoProductoId");

                    b.ToTable("productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Nombre = "Notebook Lenovo ThinkPad E14",
                            ProveedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipoProductoId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Nombre = "Mouse Logitech M720",
                            ProveedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipoProductoId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Nombre = "Router TP-Link Archer AX73",
                            ProveedorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TipoProductoId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Nombre = "Licencia Microsoft Office 365",
                            ProveedorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TipoProductoId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.ProductoEnVisita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FinGarantia")
                        .HasColumnType("date");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VisitaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VisitaId");

                    b.ToTable("productos_visitas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("67a48d6c-e3d1-4aa5-bcf8-75f6404a8c8a"),
                            Concepto = "VENTA",
                            FinGarantia = new DateOnly(2027, 10, 15),
                            NumeroSerie = "SN-LEN-12345",
                            PrecioUnitario = 130000m,
                            ProductoId = new Guid("77777777-7777-7777-7777-777777777777"),
                            VisitaId = new Guid("7c835130-a8e0-46cc-8aeb-8198a76d7222")
                        },
                        new
                        {
                            Id = new Guid("cfc3972f-981a-4c8e-94a3-cce84d90785e"),
                            Concepto = "VENTA",
                            FinGarantia = new DateOnly(2026, 10, 15),
                            NumeroSerie = "SN-LOG-45678",
                            PrecioUnitario = 35000m,
                            ProductoId = new Guid("88888888-8888-8888-8888-888888888888"),
                            VisitaId = new Guid("7c835130-a8e0-46cc-8aeb-8198a76d7222")
                        },
                        new
                        {
                            Id = new Guid("d9b12292-133a-48e5-97e1-fcf2eb39b38d"),
                            Concepto = "VENTA",
                            FinGarantia = new DateOnly(2028, 10, 20),
                            NumeroSerie = "SN-TPL-98765",
                            PrecioUnitario = 70000m,
                            ProductoId = new Guid("99999999-9999-9999-9999-999999999999"),
                            VisitaId = new Guid("7c89a11d-8d06-4608-90f9-4bd1d6d2487e")
                        },
                        new
                        {
                            Id = new Guid("e0c65170-653d-4162-83bc-81bce59be1b4"),
                            Concepto = "VENTA",
                            FinGarantia = new DateOnly(2026, 10, 23),
                            NumeroSerie = "SN-MS-11223",
                            PrecioUnitario = 180000m,
                            ProductoId = new Guid("10101010-1010-1010-1010-101010101010"),
                            VisitaId = new Guid("81a840f4-d3cf-49a1-959f-dcc3e5fbe9cf")
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<double>("Calificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("proveedores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CUIT = "30-65432198-9",
                            Calificacion = 0.0,
                            Direccion = "Av. Corrientes 2400, CABA",
                            Email = "contacto@techworld.com",
                            RazonSocial = "TechWorld S.A.",
                            Telefono = "011-4785-5566"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CUIT = "30-74569852-4",
                            Calificacion = 0.0,
                            Direccion = "Av. Rivadavia 9850, CABA",
                            Email = "ventas@pcmax.com",
                            RazonSocial = "PCMax SRL",
                            Telefono = "011-4678-1133"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Tecnico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Calificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("tecnicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cda3b5b-3c70-48c8-bc95-aafdcd88601c"),
                            Apellido = "Giménez",
                            Calificacion = 0.0,
                            DNI = "33244567",
                            Nombre = "Javier",
                            ProveedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Telefono = "+543814445566"
                        },
                        new
                        {
                            Id = new Guid("752b6aa3-4448-47eb-9edf-64c7b2fdcd02"),
                            Apellido = "Ríos",
                            Calificacion = 0.0,
                            DNI = "37456789",
                            Nombre = "Lucía",
                            ProveedorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Telefono = "+543814567891"
                        },
                        new
                        {
                            Id = new Guid("ee459fbd-509f-43cb-8068-f8c2047e03f0"),
                            Apellido = "Coronel",
                            Calificacion = 0.0,
                            DNI = "40899877",
                            Nombre = "Martín",
                            ProveedorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Telefono = "+543817894561"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.TipoProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tipos_productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nombre = "Hardware"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Nombre = "Periféricos"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Nombre = "Software"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Nombre = "Redes"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Visita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Calificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TecnicoId");

                    b.ToTable("visitas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c835130-a8e0-46cc-8aeb-8198a76d7222"),
                            Calificacion = 5.0,
                            Estado = "PENDIENTE",
                            FechaHora = new DateTime(2025, 10, 15, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            MontoTotal = 165000m,
                            Observaciones = "Adquisición de Notebook Lenovo y Mouse Logitech",
                            TecnicoId = new Guid("3cda3b5b-3c70-48c8-bc95-aafdcd88601c")
                        },
                        new
                        {
                            Id = new Guid("7c89a11d-8d06-4608-90f9-4bd1d6d2487e"),
                            Calificacion = 4.0,
                            Estado = "PENDIENTE",
                            FechaHora = new DateTime(2025, 10, 20, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            MontoTotal = 70000m,
                            Observaciones = "Adquisición de Router Tp-Link",
                            TecnicoId = new Guid("752b6aa3-4448-47eb-9edf-64c7b2fdcd02")
                        },
                        new
                        {
                            Id = new Guid("81a840f4-d3cf-49a1-959f-dcc3e5fbe9cf"),
                            Calificacion = 5.0,
                            Estado = "PENDIENTE",
                            FechaHora = new DateTime(2025, 10, 23, 11, 47, 0, 0, DateTimeKind.Unspecified),
                            MontoTotal = 180000m,
                            Observaciones = "Adquisición de Paquete Microsoft Office",
                            TecnicoId = new Guid("ee459fbd-509f-43cb-8068-f8c2047e03f0")
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Producto", b =>
                {
                    b.HasOne("Dominio.Entidades.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.TipoProducto", "TipoProducto")
                        .WithMany("Productos")
                        .HasForeignKey("TipoProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("TipoProducto");
                });

            modelBuilder.Entity("Dominio.Entidades.ProductoEnVisita", b =>
                {
                    b.HasOne("Dominio.Entidades.Producto", "Producto")
                        .WithMany("ProductosEnVisita")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Visita", "Visita")
                        .WithMany("ProductosEnVisita")
                        .HasForeignKey("VisitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("Dominio.Entidades.Tecnico", b =>
                {
                    b.HasOne("Dominio.Entidades.Proveedor", "Proveedor")
                        .WithMany("Tecnicos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Dominio.Entidades.Visita", b =>
                {
                    b.HasOne("Dominio.Entidades.Tecnico", "Tecnico")
                        .WithMany("Visitas")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Dominio.Entidades.Producto", b =>
                {
                    b.Navigation("ProductosEnVisita");
                });

            modelBuilder.Entity("Dominio.Entidades.Proveedor", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Tecnicos");
                });

            modelBuilder.Entity("Dominio.Entidades.Tecnico", b =>
                {
                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("Dominio.Entidades.TipoProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Dominio.Entidades.Visita", b =>
                {
                    b.Navigation("ProductosEnVisita");
                });
#pragma warning restore 612, 618
        }
    }
}
