// <auto-generated />
using System;
using Infraestructura.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251106180535_Modelo-Datos-V2")]
    partial class ModeloDatosV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entidades.Adquisicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("FechaAdquisicion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaFinGarantia")
                        .HasColumnType("date");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("adquisiciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("67a48d6c-e3d1-4aa5-bcf8-75f6404a8c8a"),
                            Costo = 130000m,
                            EquipoId = new Guid("77777777-7777-7777-7777-777777777777"),
                            FechaAdquisicion = new DateOnly(2025, 10, 15),
                            FechaFinGarantia = new DateOnly(2027, 10, 15),
                            NumeroSerie = "SN-LEN-12345",
                            TecnicoId = new Guid("3cda3b5b-3c70-48c8-bc95-aafdcd88601c")
                        },
                        new
                        {
                            Id = new Guid("cfc3972f-981a-4c8e-94a3-cce84d90785e"),
                            Costo = 35000m,
                            EquipoId = new Guid("88888888-8888-8888-8888-888888888888"),
                            FechaAdquisicion = new DateOnly(2025, 10, 15),
                            FechaFinGarantia = new DateOnly(2026, 10, 15),
                            NumeroSerie = "SN-LOG-45678",
                            TecnicoId = new Guid("3cda3b5b-3c70-48c8-bc95-aafdcd88601c")
                        },
                        new
                        {
                            Id = new Guid("d9b12292-133a-48e5-97e1-fcf2eb39b38d"),
                            Costo = 70000m,
                            EquipoId = new Guid("99999999-9999-9999-9999-999999999999"),
                            FechaAdquisicion = new DateOnly(2025, 10, 20),
                            FechaFinGarantia = new DateOnly(2028, 10, 20),
                            NumeroSerie = "SN-TPL-98765",
                            TecnicoId = new Guid("3cda3b5b-3c70-48c8-bc95-aafdcd88601c")
                        },
                        new
                        {
                            Id = new Guid("e0c65170-653d-4162-83bc-81bce59be1b4"),
                            Costo = 180000m,
                            EquipoId = new Guid("10101010-1010-1010-1010-101010101010"),
                            FechaAdquisicion = new DateOnly(2025, 10, 23),
                            FechaFinGarantia = new DateOnly(2026, 10, 23),
                            NumeroSerie = "SN-MS-11223",
                            TecnicoId = new Guid("3cda3b5b-3c70-48c8-bc95-aafdcd88601c")
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Equipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoEquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("TipoEquipoId");

                    b.ToTable("equipos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Nombre = "Notebook Lenovo ThinkPad E14",
                            ProveedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipoEquipoId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Nombre = "Mouse Logitech M720",
                            ProveedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipoEquipoId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Nombre = "Router TP-Link Archer AX73",
                            ProveedorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TipoEquipoId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Nombre = "Licencia Microsoft Office 365",
                            ProveedorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TipoEquipoId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Mantenimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdquisicionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Calificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoMantenimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdquisicionId");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("TipoMantenimientoId");

                    b.ToTable("mantenimientos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf58e1e4-cfc9-4dc4-8066-c82c0c62181d"),
                            AdquisicionId = new Guid("67a48d6c-e3d1-4aa5-bcf8-75f6404a8c8a"),
                            Calificacion = 4.5,
                            Costo = 0m,
                            Descripcion = "Instalación inicial del sistema operativo y software básico.",
                            Estado = "FINALIZADO",
                            Fecha = new DateOnly(2025, 11, 1),
                            TecnicoId = new Guid("3cda3b5b-3c70-48c8-bc95-aafdcd88601c"),
                            TipoMantenimientoId = new Guid("7f900d5c-45b5-424e-9a4c-7663c9acce1e")
                        },
                        new
                        {
                            Id = new Guid("9f0e8550-0c39-4cf2-8255-852c72fe9aab"),
                            AdquisicionId = new Guid("d9b12292-133a-48e5-97e1-fcf2eb39b38d"),
                            Calificacion = 4.0,
                            Costo = 15000m,
                            Descripcion = "Actualización del firmware del router para mejorar la seguridad.",
                            Estado = "FINALIZADO",
                            Fecha = new DateOnly(2026, 11, 27),
                            TecnicoId = new Guid("752b6aa3-4448-47eb-9edf-64c7b2fdcd02"),
                            TipoMantenimientoId = new Guid("9de506e3-e483-4ce1-b44e-9d66ac847f8c")
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<double>("Calificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("proveedores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CUIT = "30-65432198-9",
                            Calificacion = 4.25,
                            Direccion = "Av. Corrientes 2400, CABA",
                            Email = "contacto@techworld.com",
                            RazonSocial = "TechWorld S.A.",
                            Telefono = "011-4785-5566"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CUIT = "30-74569852-4",
                            Calificacion = 0.0,
                            Direccion = "Av. Rivadavia 9850, CABA",
                            Email = "ventas@pcmax.com",
                            RazonSocial = "PCMax SRL",
                            Telefono = "011-4678-1133"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Tecnico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Calificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nchar(8)")
                        .IsFixedLength();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.ToTable("tecnicos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cda3b5b-3c70-48c8-bc95-aafdcd88601c"),
                            Apellido = "Giménez",
                            Calificacion = 4.5,
                            DNI = "33244567",
                            Nombre = "Javier",
                            ProveedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Telefono = "+543814445566"
                        },
                        new
                        {
                            Id = new Guid("752b6aa3-4448-47eb-9edf-64c7b2fdcd02"),
                            Apellido = "Ríos",
                            Calificacion = 4.0,
                            DNI = "37456789",
                            Nombre = "Lucía",
                            ProveedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Telefono = "+543814567891"
                        },
                        new
                        {
                            Id = new Guid("ee459fbd-509f-43cb-8068-f8c2047e03f0"),
                            Apellido = "Coronel",
                            Calificacion = 0.0,
                            DNI = "40899877",
                            Nombre = "Martín",
                            ProveedorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Telefono = "+543817894561"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.TipoEquipo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tipos_equipos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nombre = "Hardware"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Nombre = "Periféricos"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Nombre = "Software"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Nombre = "Redes"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.TipoMantenimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tipos_mantenimiento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f900d5c-45b5-424e-9a4c-7663c9acce1e"),
                            Descripcion = "Instalación"
                        },
                        new
                        {
                            Id = new Guid("1b74f1e6-18a3-40a7-bd25-279f97329661"),
                            Descripcion = "Reparación en garantía"
                        },
                        new
                        {
                            Id = new Guid("97e99a3b-e5a1-4ac4-9d60-eac409c3d681"),
                            Descripcion = "Reparación fuera de garantía"
                        },
                        new
                        {
                            Id = new Guid("9de506e3-e483-4ce1-b44e-9d66ac847f8c"),
                            Descripcion = "Actualización"
                        });
                });

            modelBuilder.Entity("Dominio.Entidades.Adquisicion", b =>
                {
                    b.HasOne("Dominio.Entidades.Equipo", "Equipo")
                        .WithMany("Adquisiciones")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Tecnico", "Tecnico")
                        .WithMany("Adquisiciones")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Dominio.Entidades.Equipo", b =>
                {
                    b.HasOne("Dominio.Entidades.Proveedor", "Proveedor")
                        .WithMany("Equipos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.TipoEquipo", "TipoEquipo")
                        .WithMany("Equipos")
                        .HasForeignKey("TipoEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("Dominio.Entidades.Mantenimiento", b =>
                {
                    b.HasOne("Dominio.Entidades.Adquisicion", "Adquisicion")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("AdquisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.Tecnico", "Tecnico")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Entidades.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("TipoMantenimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adquisicion");

                    b.Navigation("Tecnico");

                    b.Navigation("TipoMantenimiento");
                });

            modelBuilder.Entity("Dominio.Entidades.Tecnico", b =>
                {
                    b.HasOne("Dominio.Entidades.Proveedor", "Proveedor")
                        .WithMany("Tecnicos")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Dominio.Entidades.Adquisicion", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("Dominio.Entidades.Equipo", b =>
                {
                    b.Navigation("Adquisiciones");
                });

            modelBuilder.Entity("Dominio.Entidades.Proveedor", b =>
                {
                    b.Navigation("Equipos");

                    b.Navigation("Tecnicos");
                });

            modelBuilder.Entity("Dominio.Entidades.Tecnico", b =>
                {
                    b.Navigation("Adquisiciones");

                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("Dominio.Entidades.TipoEquipo", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("Dominio.Entidades.TipoMantenimiento", b =>
                {
                    b.Navigation("Mantenimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
